name: PR
on:
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review, synchronize, edited]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.13.1'

      - name: Set up GitHub Package Registry token
        run: |
          echo @harness:registry=https://npm.pkg.github.com > .npmrc
          echo "//npm.pkg.github.com/:_authToken="$GIT_BOT_TOKEN >> .npmrc
          echo always-auth=true >> .npmrc
        env:
          GIT_BOT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Packages
        run: yarn

      - name: Lint Check
        run: yarn lint

  messagecheck:
    name: Title Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Title Check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo $PR_TITLE
          node ./scripts/lint-commit-message.js "$PR_TITLE"

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.13.1'

      - name: Set up GitHub Package Registry token
        run: |
          echo @harness:registry=https://npm.pkg.github.com > .npmrc
          echo "//npm.pkg.github.com/:_authToken="$GIT_BOT_TOKEN >> .npmrc
          echo always-auth=true >> .npmrc
        env:
          GIT_BOT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Packages
        run: yarn

      - name: Type check
        run: yarn typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.13.1'

      - name: Set up GitHub Package Registry token
        run: |
          echo @harness:registry=https://npm.pkg.github.com > .npmrc
          echo "//npm.pkg.github.com/:_authToken="$GIT_BOT_TOKEN >> .npmrc
          echo always-auth=true >> .npmrc
        env:
          GIT_BOT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Packages
        run: yarn

      - name: Prettier format check
        run: yarn pretty
