name: Publish

on:
  push:
    tags:
      - '*'
  release:
    types:
      - published
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo {{ toJSON(github.event) }}
